# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Location.destroy_all
Oxford.destroy_all
Treatment.destroy_all
Meeting.destroy_all

# Locations
salem = Location.create(name: "Salem", zip: 24153, county: "Salem")
hanover = Location.create(name: "Hanover", zip: 23069, county: "Hanover")
amherst = Location.create(name: "Amherst", zip: 24521, county: "Amherst")
galax = Location.create(name: "Galax", zip: 24333, county: "Galax")
alexandria = Location.create(name: "Alexandria", zip: 22304, county: "Alexandria")
arlington = Location.create(name: "Arlington", zip: 22206, county: "Arlington")
charlottesville = Location.create(name: "Charlottesville", zip: 22903, county: "Charlottesville")
chesapeake = Location.create(name: "Chesapeake", zip: 23324, county: "Chesapeake")
chesterfield = Location.create(name: "Chesterfield", zip: 23236, county: "Chesterfield")
culpeper = Location.create(name: "Culpeper", zip: 22701, county: "Culpeper")
annandale = Location.create(name: "Annandale", zip: 22003, county: "Fairfax")
chantilly = Location.create(name: "Chantilly", zip: 20151, county: "Fairfax")
herndon = Location.create(name: "Herndon", zip: 20170, county: "Fairfax")
fairfax = Location.create(name: "Fairfax", zip: 22031, county: "Fairfax")
mclean = Location.create(name: "McLean", zip: 22101, county: "Fairfax")
springfield = Location.create(name: "Springfield", zip: 22151, county: "Fairfax")
vienna = Location.create(name: "Vienna", zip: 22180, county: "Fairfax")
falls_church = Location.create(name: "Falls Church", zip: 22041, county: "Fairfax")
winchester_frederick = Location.create(name: "Winchester", zip: 22601, county: "Frederick")
hampton = Location.create(name: "Hampton", zip: 23664, county: "Hampton")
harrisonburg = Location.create(name: "Harrisonburg", zip: 22802, county: "Harrisonburg")
glen_allen = Location.create(name: "Glen Allen", zip: 23060, county: "Henrico")
henrico = Location.create(name: "Henrico", zip: 23229, county: "Henrico")
williamsburg_jc = Location.create(name: "Williamsburg", zip: 23188, county: "James City")
sterling = Location.create(name: "Sterling", zip: 20164, county: "Loudoun")
lynchburg = Location.create(name: "Lynchburg", zip: 24502, county: "Lynchburg")
christianburg = Location.create(name: "Christianburg", zip: 24073, county: "Montgomery")
norfolk = Location.create(name: "Norfolk", zip: 23503, county: "Norfolk")
petersburg = Location.create(name: "Petersburg", zip: 23805, county: "Petersburg")
portsmouth = Location.create(name: "Portsmouth", zip: 23702, county: "Portsmouth")
manassass = Location.create(name: "Manassass", zip: 20110, county: "Prince William")
radford = Location.create(name: "Radford", zip: 24141, county: "Radford")
richmond = Location.create(name: "Richmond", zip: 23222, county: "Richmond")
roanoke = Location.create(name: "Roanoke", zip: 24012, county: "Roanoke")
fredricksburg = Location.create(name: "Fredericksburg", zip: 22405, county: "Spotsylvania")
virginia_beach = Location.create(name: "Virginia Beach", zip: 23456, county: "Virginia Beach")
winchester_winchester = Location.create(name: "Winchester", zip: 22601, county: "Winchester")
williamsburg_york = Location.create(name: "Williamsburg", zip: 23185, county: "York")






# Oxfords 





belle_haven = Oxford.create(name: "Belle Haven", location_id: alexandria.id, gender: "Male")
diva = Oxford.create(name: "Diva", location_id: alexandria.id, gender: "Female")
glebe_road = Oxford.create(name: "Glebe Road", location_id: alexandria.id, gender: "Male")
landmark = Oxford.create(name: "Landmark", location_id: alexandria.id, gender: "Male")
mt_vernon_square = Oxford.create(name: "Mt Vernon Square", location_id: alexandria.id, gender: "Male")
ballston = Oxford.create(name: "Ballston", location_id: arlington.id, gender: "Male")
glebewood = Oxford.create(name: "Glebewood", location_id: arlington.id, gender: "Male")
glen_carlyn = Oxford.create(name: "Glen Carlyn", location_id: arlington.id, gender: "Female")
thomas_street = Oxford.create(name: "Thomas Street", location_id: arlington.id, gender: "Male")
waverly_hills = Oxford.create(name: "Waverly Hills", location_id: arlington.id, gender: "Male")
forest_hills_park = Oxford.create(name: "Forest Hills Park", location_id: charlottesville.id, gender: "Male")
frys_spring = Oxford.create(name: "Frys Spring", location_id: charlottesville.id, gender: "Female")
pen_park = Oxford.create(name: "Pen Park", location_id: charlottesville.id, gender: "Male")
wakefield = Oxford.create(name: "Wakefield", location_id: charlottesville.id, gender: "Male")
washington_park = Oxford.create(name: "Washington Park", location_id: charlottesville.id, gender: "Male")
chesapeake_house = Oxford.create(name: "Chesapeake", location_id: chesapeake.id, gender: "Male")
greenbriar = Oxford.create(name: "Greenbriar", location_id: chesapeake.id, gender: "Male")
bon_air = Oxford.create(name: "Bon Air", location_id: chesterfield.id, gender: "Female")
chester = Oxford.create(name: "Chester", location_id: chesterfield.id, gender: "Male")
cottonwood = Oxford.create(name: "Cottonwood", location_id: culpeper.id, gender: "Male")
endurance = Oxford.create(name: "Endurance", location_id: annandale.id, gender: "Male")
pence_court = Oxford.create(name: "Pence Court", location_id: annandale.id, gender: "Male")
crossman = Oxford.create(name: "Crossman", location_id: annandale.id, gender: "Male")
ravensworth = Oxford.create(name: "Ravensworth", location_id: annandale.id, gender: "Male")
columbia_pike = Oxford.create(name: "Columbia Pike", location_id: annandale.id, gender: "Male")
manor = Oxford.create(name: "Manor", location_id: annandale.id, gender: "Male")
briarwood2 = Oxford.create(name: "Briarwood 2", location_id: chantilly.id, gender: "Male")
new_beginning = Oxford.create(name: "New Beginning", location_id: chantilly.id, gender: "Male")
little_river = Oxford.create(name: "Little River", location_id: fairfax.id, gender: "Male")
manchester_woods = Oxford.create(name: "Manchester Woods", location_id: fairfax.id, gender: "Male")
beau_lane = Oxford.create(name: "Beau Lane", location_id: fairfax.id, gender: "Male")
fair_oaks = Oxford.create(name: "Fair Oaks", location_id: fairfax.id, gender: "Male")
prosperity = Oxford.create(name: "Prosperity", location_id: fairfax.id, gender: "Male")
fairhill = Oxford.create(name: "Fairhill", location_id: fairfax.id, gender: "Male")
south_lee = Oxford.create(name: "South Lee", location_id: falls_church.id, gender: "Male")
berkly_park = Oxford.create(name: "Berkly Park", location_id: falls_church.id, gender: "Male")
forest_glen = Oxford.create(name: "Forest Glen", location_id: falls_church.id, gender: "Male")
annadale_house = Oxford.create(name: "Annandale", location_id: falls_church.id, gender: "Male")
mooreland = Oxford.create(name: "Mooreland", location_id: falls_church.id, gender: "Male")
merrifield = Oxford.create(name: "Merrifield", location_id: falls_church.id, gender: "Male")
baileys_crossroads = Oxford.create(name: "Bailey's Crossroads", location_id: falls_church.id, gender: "Male")
briar_patch = Oxford.create(name: "Briar Patch", location_id: herndon.id, gender: "Male")
kings_manor = Oxford.create(name: "Kings Manor", location_id: mclean.id, gender: "Male")
chain_bridge = Oxford.create(name: "Chain Bridge", location_id: mclean.id, gender: "Male")
springfield_house = Oxford.create(name: "Springfield", location_id: springfield.id, gender: "Male")
pike_place = Oxford.create(name: "Pike Place", location_id: vienna.id, gender: "Male")
tysons_corner = Oxford.create(name: "Tysons Corner", location_id: vienna.id, gender: "Male")
wesleyan = Oxford.create(name: "Wesleyan", location_id: vienna.id, gender: "Male")
brilyn = Oxford.create(name: "Brilyn", location_id: vienna.id, gender: "Male")
oakdale_park = Oxford.create(name: "Oakdale Park", location_id: vienna.id, gender: "Male")
chapel_hill = Oxford.create(name: "Chapel Hill", location_id: annandale.id, gender: "Female")
brandy_jo = Oxford.create(name: "Brandy Jo", location_id: annandale.id, gender: "Female")
hermosa = Oxford.create(name: "Hermosa", location_id: fairfax.id, gender: "Female")
pentagon = Oxford.create(name: "Pentagon", location_id: fairfax.id, gender: "Female")
hunter_street = Oxford.create(name: "Hunter Street", location_id: fairfax.id, gender: "Female")
angel_park = Oxford.create(name: "Angel Park", location_id: herndon.id, gender: "Female")
melita = Oxford.create(name: "Melita", location_id: springfield.id, gender: "Female")
jameswood = Oxford.create(name: "Jameswood", location_id: winchester_frederick.id, gender: "Male")
beall_drive = Oxford.create(name: "Beall Drive", location_id: hampton.id, gender: "Male")
brookfield = Oxford.create(name: "Brookfield", location_id: hampton.id, gender: "Male")
hampton_house = Oxford.create(name: "Hampton", location_id: hampton.id, gender: "Male")
little_black = Oxford.create(name: "Little Black", location_id: hampton.id, gender: "Male")
lynnhaven = Oxford.create(name: "Lynnhaven", location_id: hampton.id, gender: "Female")
peninsula = Oxford.create(name: "Peninsula", location_id: hampton.id, gender: "Male")
summit = Oxford.create(name: "Summit", location_id: harrisonburg.id, gender: "Male")
trillium = Oxford.create(name: "Trillium", location_id: harrisonburg.id, gender: "Female")
mountain_road = Oxford.create(name: "Mountain Road", location_id: glen_allen.id, gender: "Female")
tuckahoe = Oxford.create(name: "Tuckahoe", location_id: henrico.id, gender: "Male")
blossom = Oxford.create(name: "Blossom", location_id: williamsburg_jc.id, gender: "Male")
deer_springs = Oxford.create(name: "Deer Springs", location_id: williamsburg_jc.id, gender: "Male")
jamestown = Oxford.create(name: "Jamestown", location_id: williamsburg_jc.id, gender: "Male")
williamsburg_house = Oxford.create(name: "Williamsburg", location_id: williamsburg_jc.id, gender: "Male")
forest_ridge = Oxford.create(name: "Forest Ridge", location_id: sterling.id, gender: "Male")
north_upton = Oxford.create(name: "North Upton", location_id: sterling.id, gender: "Male")
sterling_house = Oxford.create(name: "Sterling", location_id: sterling.id, gender: "Male")
sugarland = Oxford.create(name: "Sugarland", location_id: sterling.id, gender: "Male")
wyman = Oxford.create(name: "Wyman", location_id: sterling.id, gender: "Male")
birdie = Oxford.create(name: "Birdie", location_id: lynchburg.id, gender: "Female")
kyber = Oxford.create(name: "Kyber", location_id: lynchburg.id, gender: "Male")
meg_davis = Oxford.create(name: "Meg Davis", location_id: lynchburg.id, gender: "Female")
scholar = Oxford.create(name: "Scholar", location_id: lynchburg.id, gender: "Male")
new_river = Oxford.create(name: "New River", location_id: christianburg.id, gender: "Female")
bayview_gardens = Oxford.create(name: "Bayview Gardens", location_id: norfolk.id, gender: "Male")
little_creek = Oxford.create(name: "Little Creek", location_id: norfolk.id, gender: "Female")
new_horizon = Oxford.create(name: "New Horizon", location_id: norfolk.id, gender: "Male")
princess_anne = Oxford.create(name: "Princess Anne", location_id: norfolk.id, gender: "Female")
seaview = Oxford.create(name: "Seaview", location_id: norfolk.id, gender: "Male")
appomattox = Oxford.create(name: "Appomatox", location_id: petersburg.id, gender: "Male")
gosport = Oxford.create(name: "Gosport", location_id: portsmouth.id, gender: "Male")
westhaven_park = Oxford.create(name: "Westhaven Park", location_id: portsmouth.id, gender: "Female")
court_square = Oxford.create(name: "Court Square", location_id: manassass.id, gender: "Male")
liberia_woods = Oxford.create(name: "Liberia Woods", location_id: manassass.id, gender: "Female")
manassas_house = Oxford.create(name: "Manassas", location_id: manassass.id, gender: "Male")
roseberry = Oxford.create(name: "Roseberry", location_id: manassass.id, gender: "Female")
sudley_manor = Oxford.create(name: "Sudley Manor", location_id: manassass.id, gender: "Male")
thomas_li = Oxford.create(name: "Thomas Li", location_id: manassass.id, gender: "Male")
wellington = Oxford.create(name: "Wellington", location_id: manassass.id, gender: "Male")
radford_house = Oxford.create(name: "Radford", location_id: radford.id, gender: "Male")
willow_woods = Oxford.create(name: "Willow Woods", location_id: radford.id, gender: "Female")
clay_street = Oxford.create(name: "Clay Street", location_id: richmond.id, gender: "Male")
serenity_path = Oxford.create(name: "Serenity Path", location_id: richmond.id, gender: "Male")
ramekin = Oxford.create(name: "Ramekin", location_id: richmond.id, gender: "Male")
river_city = Oxford.create(name: "River City", location_id: richmond.id, gender: "Male")
woodland_heights = Oxford.create(name: "Woodland Heights", location_id: richmond.id, gender: "Male")
carver = Oxford.create(name: "Carver", location_id: richmond.id, gender: "Male")
brookland_park = Oxford.create(name: "Brookland Park", location_id: richmond.id, gender: "Male")
pollard_park_li = Oxford.create(name: "Pollard Park Li", location_id: richmond.id, gender: "Female")
edgehill = Oxford.create(name: "Edgehill", location_id: richmond.id, gender: "Female")
valley_view = Oxford.create(name: "Valley View", location_id: roanoke.id, gender: "Male")
horizon = Oxford.create(name: "Horizon", location_id: roanoke.id, gender: "Male")
wasena = Oxford.create(name: "Wasena", location_id: roanoke.id, gender: "Male")
elm_street = Oxford.create(name: "Elm Street", location_id: roanoke.id, gender: "Male")
sunnyside = Oxford.create(name: "Sunnyside", location_id: roanoke.id, gender: "Male")
roanoke_river = Oxford.create(name: "Roanoke River", location_id: roanoke.id, gender: "Male")
kenwood = Oxford.create(name: "Kenwood", location_id: roanoke.id, gender: "Male")
mill_mountain = Oxford.create(name: "Mill Mountain", location_id: roanoke.id, gender: "Male")
old_dominion = Oxford.create(name: "Old Dominion", location_id: roanoke.id, gender: "Male")
fenix = Oxford.create(name: "Fenix", location_id: roanoke.id, gender: "Female")
star_city = Oxford.create(name: "Star City", location_id: roanoke.id, gender: "Female")
raleigh_court = Oxford.create(name: "Raleigh Court", location_id: roanoke.id, gender: "Female")
tarpley_park = Oxford.create(name: "Tarpley Park", location_id: roanoke.id, gender: "Female")
rising_sun = Oxford.create(name: "Rising Sun", location_id: fredricksburg.id, gender: "Male")
orchid = Oxford.create(name: "Orchid", location_id: fredricksburg.id, gender: "Male")
hazel_run = Oxford.create(name: "Hazel Run", location_id: fredricksburg.id, gender: "Male")
plaza = Oxford.create(name: "Plaza", location_id: virginia_beach.id, gender: "Male")
coastal = Oxford.create(name: "Coastal", location_id: virginia_beach.id, gender: "Male")
salem_house = Oxford.create(name: "Salem", location_id: virginia_beach.id, gender: "Male")
oceana = Oxford.create(name: "Oceana", location_id: virginia_beach.id, gender: "Male")
tidewater = Oxford.create(name: "Tidewater", location_id: virginia_beach.id, gender: "Male")
golden_maple = Oxford.create(name: "Golden Maple", location_id: virginia_beach.id, gender: "Male")
neptune = Oxford.create(name: "Neptune", location_id: virginia_beach.id, gender: "Male")
poseidon = Oxford.create(name: "Poseidon", location_id: virginia_beach.id, gender: "Male")
lake_smith = Oxford.create(name: "Lake Smith", location_id: virginia_beach.id, gender: "Male")
triton = Oxford.create(name: "Triton", location_id: virginia_beach.id, gender: "Male")
oceanfront = Oxford.create(name: "Oceanfront", location_id: virginia_beach.id, gender: "Male")
nauticus = Oxford.create(name: "Nauticus", location_id: virginia_beach.id, gender: "Male")
luna = Oxford.create(name: "Luna", location_id: virginia_beach.id, gender: "Female")
pembroke = Oxford.create(name: "Pembroke", location_id: virginia_beach.id, gender: "Female")
coral = Oxford.create(name: "Coral", location_id: virginia_beach.id, gender: "Female")
victoria = Oxford.create(name: "victoria", location_id: virginia_beach.id, gender: "Female")
hera = Oxford.create(name: "Hera", location_id: virginia_beach.id, gender: "Female")
fairview_park = Oxford.create(name: "Fairview Park", location_id: winchester_winchester.id, gender: "Male")
hill_top_heights = Oxford.create(name: "Hill Top Heights", location_id: winchester_winchester.id, gender: "Male")
north_ave = Oxford.create(name: "North Ave", location_id: winchester_winchester.id, gender: "Male")
old_town = Oxford.create(name: "Old Town", location_id: winchester_winchester.id, gender: "Male")
pleasant_valley = Oxford.create(name: "Pleasant Valley", location_id: winchester_winchester.id, gender: "Male")
winchester_heights = Oxford.create(name: "Winchester Heights", location_id: winchester_winchester.id, gender: "Male")
douglass_park = Oxford.create(name: "Douglass Park", location_id: winchester_winchester.id, gender: "Male")
amherst_street = Oxford.create(name: "Amherst Street", location_id: winchester_winchester.id, gender: "Male")
shenandoah_valley = Oxford.create(name: "Shenandoah Valley", location_id: winchester_winchester.id, gender: "Female")
south_cameron = Oxford.create(name: "South Cameron", location_id: winchester_winchester.id, gender: "Female")
apple_blossom = Oxford.create(name: "Apple Blossom", location_id: winchester_winchester.id, gender: "Female")
piccadilly_place = Oxford.create(name: "Piccadilly Place", location_id: winchester_winchester.id, gender: "Female")
serenity_park = Oxford.create(name: "Serenity Park", location_id: winchester_winchester.id, gender: "Female")
york = Oxford.create(name: "York", location_id: williamsburg_york.id, gender: "Male")






# Treatments



galax = Treatment.create(name: "Life Center at Galax", location_id: galax.id)
horizon = Treatment.create(name: "Horizon Behavioral Health - Courtland Wellness Center", location_id: lynchburg.id)
pathways = Treatment.create(name: "Pathways Recovery Lodge", location_id: amherst.id)
phoenix_house = Treatment.create(name: "Phoenix House", location_id: arlington.id)
bethany_hall = Treatment.create(name: "Bethany Hall", location_id: roanoke.id)
boxwood = Treatment.create(name: "Boxwood Detox & Recovery Program", location_id: culpeper.id)

williamsville = Treatment.create(name: "Williamsville Wellness Center", location_id: hanover.id)
sefp = Treatment.create(name: "Southeastern Family Project", location_id: hampton.id)
vamc_satp = Treatment.create(name: "Veterans Affairs Medical Center - Substance Abuse Treatment Program", location_id: salem.id)
btg = Treatment.create(name: "Bridging the Gaps Inc - Substance Abuse and Outpatient Servs", location_id: winchester_winchester.id)
sagebrush = Treatment.create(name: "Sagebrush Treatment Inc - Inpatient/Residential", location_id: vienna.id)
cornerstones = Treatment.create(name: "Cornerstones", location_id: chantilly.id)
crossroads = Treatment.create(name: "Crossroads", location_id: alexandria.id)
new_generations = Treatment.create(name: "New Generations - Specialized Women", location_id: vienna.id)
new_beginning = Treatment.create(name: "A New Beginning", location_id: chantilly.id)
mohr_center = Treatment.create(name: "Mohr Center", location_id: charlottesville.id)
sudcc = Treatment.create(name: "SUDCC - Army Substance Abuse Program", location_id: alexandria.id)
mt_regis = Treatment.create(name: "Mt. Regis Center", location_id: salem.id)

#Insurance Types

tricare = InsuranceType.create(name: "Tricare")
private_insurance = InsuranceType.create(name: "Private")
medicaid = InsuranceType.create(name: "Medicaid")
state = InsuranceType.create(name: "State")

#InsuranceTreatment

#TRICARE

InsuranceTreatment.create(treatment_id: btg.id, insurance_type_id: tricare.id)
InsuranceTreatment.create(treatment_id: sagebrush.id, insurance_type_id: tricare.id)
InsuranceTreatment.create(treatment_id: cornerstones.id, insurance_type_id: tricare.id)
InsuranceTreatment.create(treatment_id: crossroads.id, insurance_type_id: tricare.id)
InsuranceTreatment.create(treatment_id: new_beginning.id, insurance_type_id: tricare.id)
InsuranceTreatment.create(treatment_id: new_generations.id, insurance_type_id: tricare.id)
InsuranceTreatment.create(treatment_id: sudcc.id, insurance_type_id: tricare.id)
InsuranceTreatment.create(treatment_id: vamc_satp.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: btg.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: horizon.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: mt_regis.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: pathways.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: phoenix_house.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: sagebrush.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: cornerstones.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: crossroads.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: new_beginning.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: new_generations.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: mohr_center.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: williamsville.id, insurance_type_id: private_insurance.id)
InsuranceTreatment.create(treatment_id: galax.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: vamc_satp.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: horizon.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: pathways.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: phoenix_house.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: bethany_hall.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: boxwood.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: cornerstones.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: crossroads.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: new_beginning.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: new_generations.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: mohr_center.id, insurance_type_id: medicaid.id)
InsuranceTreatment.create(treatment_id: williamsville.id, insurance_type_id: medicaid.id)


Meeting.create(name: "Dr Bobs", date: "Monday", gender: "Male")
Meeting.create(name: "12&12", date: "Monday", gender: "Female")
Meeting.create(name: "AA Angels", date: "Tuesday", gender: "Male")
Meeting.create(name: "A Sense of Belonging", date: "Tuesday", gender: "Female")
Meeting.create(name: "3B’s Meeting (Beginner Big Book)", date: "Wednesday", gender: "Male")
Meeting.create(name: "AA Slogans", date: "Wednesday", gender: "Female")
Meeting.create(name: "A Backwards Glance", date: "Thursday", gender: "Male")
Meeting.create(name: "AA 101", date: "Thursday", gender: "Female")
Meeting.create(name: "Accord Group", date: "Friday", gender: "Male")
Meeting.create(name: "Centreville Group", date: "Friday", gender: "Female")
Meeting.create(name: "Early Birds", date: "Saturday", gender: "Male")
Meeting.create(name: "Early Risers", date: "Saturday", gender: "Female")
Meeting.create(name: "Fairfax Station", date: "Sunday", gender: "Male")
Meeting.create(name: "Fairfax Women", date: "Sunday", gender: "Female")


ebyan = User.create(username: "ebyan", sober_date: 0)